name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-177.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  firebase_ui_firestore: ^1.6.3
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  firebase_remote_config: ^4.4.7
  cloud_functions: ^4.7.6
  firebase_performance: ^0.9.4+7
  firebase_ui_auth: ^1.14.0
  firebase_app_check: ^0.2.2+7
  firebase_in_app_messaging: ^0.7.5+7
  firebase_app_installations: ^0.2.5+7
  cloud_firestore_odm: ^1.0.0-dev.84
  firebase_database: ^10.5.7
  firebase_ml_model_downloader: ^0.2.5+6
  # firebase_ui_storage: ^2.0.4
  # firebase_ui_localizations: ^1.11.0
  # firebase_ui_database: ^1.4.3
  # flutterfire_installations: ^0.1.0
  # firebase_ml_custom: ^0.2.0+3
  # firebase_ui_shared: ^1.4.1
  # firebase_ui_oauth_twitter: ^1.2.20
  # firebase_ui_oauth_facebook: ^1.2.20
  # _flutterfire_internals: ^1.3.35
  # firebase_ui_oauth_google: ^1.3.2
  # firebase_performance_platform_interface: ^0.1.4+35
  # firebase_ui_oauth_apple: ^1.2.20
  # firebase_performance_web: ^0.1.6+7 # not use
  # firebase_auth_web: ^5.12.0 # not use
  # firebase_storage_web: ^3.9.7 # not use
  # firebase_messaging_web: ^3.8.7 # not use
  # firebase_analytics_web: ^0.5.7+7 # not use
  # firebase_core_web: ^2.17.0 # not use
  # cloud_functions_web: ^4.9.6 # not use
  # cloud_firestore_web: ^3.12.5 # not use
  # firebase_vertexai: ^0.1.1
  # firebase_ui_oauth: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
